name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: 79.143.94.91
        port: 2222
        username: kevin
        key: ${{secrets.PRIVATE_KEY}}
        script: "cd /var/www/html/proyecto-tests-design; git pull; npm run build"
